AllCops:
  Exclude:
    - works_cited.gemspec
  NewCops: enable
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'before', 'let']
  Exclude:
    - 'spec/dummy/db/schema.rb'
Metrics/MethodLength:
  IgnoredMethods: ['change']