inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - works_cited.gemspec
    - spec/dummy/db/schema.rb
    - spec/dummy/db/migrate/*
    - vendor/**/*

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'before', 'let']
  Exclude:
    - spec/*
    - spec/*/*

Metrics/MethodLength:
  AllowedMethods: ['change']

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
