 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/doodads", type: :request do
  
  # Doodad. As you add validations to Doodad, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Doodad.create! valid_attributes
      get doodads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      doodad = Doodad.create! valid_attributes
      get doodad_url(doodad)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_doodad_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      doodad = Doodad.create! valid_attributes
      get edit_doodad_url(doodad)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Doodad" do
        expect {
          post doodads_url, params: { doodad: valid_attributes }
        }.to change(Doodad, :count).by(1)
      end

      it "redirects to the created doodad" do
        post doodads_url, params: { doodad: valid_attributes }
        expect(response).to redirect_to(doodad_url(Doodad.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Doodad" do
        expect {
          post doodads_url, params: { doodad: invalid_attributes }
        }.to change(Doodad, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post doodads_url, params: { doodad: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested doodad" do
        doodad = Doodad.create! valid_attributes
        patch doodad_url(doodad), params: { doodad: new_attributes }
        doodad.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the doodad" do
        doodad = Doodad.create! valid_attributes
        patch doodad_url(doodad), params: { doodad: new_attributes }
        doodad.reload
        expect(response).to redirect_to(doodad_url(doodad))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        doodad = Doodad.create! valid_attributes
        patch doodad_url(doodad), params: { doodad: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested doodad" do
      doodad = Doodad.create! valid_attributes
      expect {
        delete doodad_url(doodad)
      }.to change(Doodad, :count).by(-1)
    end

    it "redirects to the doodads list" do
      doodad = Doodad.create! valid_attributes
      delete doodad_url(doodad)
      expect(response).to redirect_to(doodads_url)
    end
  end
end
